#!/bin/bash

# a "web server" serving a single character (.) with log functionality.
# -v verboose -n noresolve -l listen -p port -q 1 quitsomething.
# >> tmplogg2 2>&1 = log funtion with stdout AND errout.

echo 'Serving "." @ localhost 4616'
while true; do
  echo -e "HTTP/1.1 200 OK\n\n ." | nc -v -n -l -p 4616 -q 1 >> tmplugg2 2>&1
date >> tmplugg2
echo "" >> tmplugg2
done
